version: "3.3"

services:
    mssql-db:
      build: ./db/docker
      #image: mcr.microsoft.com/mssql/server
      ports:
        - 2323:1433
      environment: 
        ACCEPT_EULA: "Y"
        SA_PASSWORD: HelloW0rld  
        MSSQL_DB: bookDb
  
    application:
      image: dpankov91/todoapi
      environment: 
        ASPNETCORE_ENVIRONMENT: Development
        DatabaseConnectionString: Server=mssql-db;Database=bookDb;UserId=sa;Password=HelloW0rld;
      depends_on: 
        - mssql-db
      ports: 
        - 5151:80

    flyway:
      image: flyway/flyway
      command: migrate
      volumes:
        - ./db:/flyway/sql
        - ./db:/flyway/conf
      depends_on:
        - mssql-db
