CREATE TABLE Author(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(75) NOT NULL
)

CREATE TABLE Genre(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(75) NOT NULL
)

CREATE TABLE Book(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(75) NOT NULL,
    PublishYear DateTime NOT NULL
)